server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8010
          predicates:
            - Path=/api/university/user/**

        - id: student-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/university/student/**

        - id: teacher-service
          uri: http://localhost:8030
          predicates:
            - Path=/api/university/teacher/**

        - id: course-service
          uri: http://localhost:8040
          predicates:
            - Path=/api/university/course/**

        - id: attendance-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/university/attendance/**

        - id: grade-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/university/grade/**

okta:
  oauth2:
    issuer: https://dev-35643909.okta.com/oauth2/default
    audience: api://default
    client-id: 0oabnszncb9VmS6Jz5d7
    client-secret: 94uiGWoiISfptGSmyZ8slRFZmLAlzpMNTT6IwVzxhOJrif46U8fJmQt73ee8lnxl
    scopes: openid, profile, email, offline_access