eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: course-service

okta:
  oauth2:
    issuer: https://dev-35643909.okta.com/oauth2/default
    audience: api://default