server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: user-service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
