server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-35643909.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 0oabnszncb9VmS6Jz5d7
            clientSecret: 94uiGWoiISfptGSmyZ8slRFZmLAlzpMNTT6IwVzxhOJrif46U8fJmQt73ee8lnxl

        provider:
          okta:
            issuerUri: https://dev-35643909.okta.com/oauth2/default
okta:
  oauth2:
    issuer: https://dev-35643909.okta.com/oauth2/default
    audience: api://default

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
